import "./globals.css";
import "./tailwindClasses.css";
import "./page.module.css";
import LayoutProvider from "@/components/LayoutProvider";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: { default: "MatchBox", template: "%s | MatchBox" },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  );
}
